POST http://localhost:8080/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{ "firstName": "Foo", "lastName": "Bar" }

###
GET http://localhost:8080/guests HTTP/1.1
Accept: application/json

###
GET http://localhost:8080/guests HTTP/1.1
Accept: application/json
Authorization: Basic admin:admin

###
GET http://localhost:8080/guests HTTP/1.1
Accept: application/json
Authorization: Basic YWRtaW46UEBzc3cwcmQh
