GET http://services.odata.org/V4/Northwind/Northwind.svc/Customers HTTP/1.1
Accept: application/json

###

GET http://services.odata.org/V4/Northwind/Northwind.svc/Customers HTTP/1.1
Accept: application/atom+xml

###

GET http://services.odata.org/V4/Northwind/Northwind.svc/Customers?$filter=Country%20eq%20%27Germany%27 HTTP/1.1
Accept: application/json
