export class HangmanLogic {
  private static words = [
    'abandon',        'ability',        'abortion',         'absence',
    'absolute',       'absolutely',     'academic',         'accident',
    'accompany',      'accomplish',     'according',        'account',
    'accurate',       'achieve',        'achievement',      'acknowledge',
    'acquire',        'activist',       'activity',         'actress',
    'actually',       'addition',       'additional',       'address',
    'adequate',       'adjustment',     'administration',   'administrator',
    'admission',      'adolescent',     'advance',          'advanced',
    'advantage',      'adventure',      'advertising',      'adviser',
    'advocate',       'African',        'African-American', 'afternoon',
    'against',        'aggressive',     'agreement',        'agricultural',
    'aircraft',       'airline',        'airport',          'alcohol',
    'alliance',       'already',        'alternative',      'although',
    'amazing',        'American',       'analysis',         'analyst',
    'analyze',        'ancient',        'anniversary',      'announce',
    'another',        'anticipate',     'anxiety',          'anybody',
    'anymore',        'anything',       'anywhere',         'apartment',
    'apparent',       'apparently',     'appearance',       'application',
    'appoint',        'appointment',    'appreciate',       'approach',
    'appropriate',    'approval',       'approve',          'approximately',
    'architect',      'argument',       'arrange',          'arrangement',
    'arrival',        'article',        'artistic',         'assault',
    'assessment',     'assignment',     'assistance',       'assistant',
    'associate',      'association',    'assumption',       'athlete',
    'athletic',       'atmosphere',     'attempt',          'attention',
    'attitude',       'attorney',       'attract',          'attractive',
    'attribute',      'audience',       'authority',        'available',
    'average',        'awareness',      'background',       'balance',
    'barrier',        'baseball',       'basically',        'basketball',
    'bathroom',       'battery',        'beautiful',        'because',
    'bedroom',        'beginning',      'behavior',         'believe',
    'beneath',        'benefit',        'besides',          'between',
    'billion',        'biological',     'birthday',         'blanket',
    'bombing',        'boundary',       'boyfriend',        'breakfast',
    'breathe',        'briefly',        'brilliant',        'British',
    'brother',        'building',       'business',         'cabinet',
    'calculate',      'campaign',       'Canadian',         'candidate',
    'capability',     'capable',        'capacity',         'capital',
    'captain',        'capture',        'careful',          'carefully',
    'carrier',        'category',       'Catholic',         'ceiling',
    'celebrate',      'celebration',    'celebrity',        'central',
    'century',        'ceremony',       'certain',          'certainly',
    'chairman',       'challenge',      'chamber',          'champion',
    'championship',   'changing',       'channel',          'chapter',
    'character',      'characteristic', 'characterize',     'charity',
    'chemical',       'chicken',        'childhood',        'Chinese',
    'chocolate',      'cholesterol',    'Christian',        'Christmas',
    'cigarette',      'circumstance',   'citizen',          'civilian',
    'classic',        'classroom',      'clearly',          'climate',
    'clinical',       'closely',        'clothes',          'clothing',
    'cluster',        'coalition',      'cognitive',        'collapse',
    'colleague',      'collect',        'collection',       'collective',
    'college',        'colonial',       'combination',      'combine',
    'comfort',        'comfortable',    'command',          'commander',
    'comment',        'commercial',     'commission',       'commitment',
    'committee',      'communicate',    'communication',    'community',
    'company',        'compare',        'comparison',       'compete',
    'competition',    'competitive',    'competitor',       'complain',
    'complaint',      'complete',       'completely',       'complex',
    'complicated',    'component',      'compose',          'composition',
    'comprehensive',  'computer',       'concentrate',      'concentration',
    'concept',        'concern',        'concerned',        'concert',
    'conclude',       'conclusion',     'concrete',         'condition',
    'conduct',        'conference',     'confidence',       'confident',
    'confirm',        'conflict',       'confront',         'confusion',
    'Congress',       'congressional',  'connect',          'connection',
    'consciousness',  'consensus',      'consequence',      'conservative',
    'consider',       'considerable',   'consideration',    'consist',
    'consistent',     'constant',       'constantly',       'constitute',
    'constitutional', 'construct',      'construction',     'consultant',
    'consume',        'consumer',       'consumption',      'contact',
    'contain',        'container',      'contemporary',     'content',
    'contest',        'context',        'continue',         'continued',
    'contract',       'contrast',       'contribute',       'contribution',
    'control',        'controversial',  'controversy',      'convention',
    'conventional',   'conversation',   'convert',          'conviction',
    'convince',       'cooking',        'cooperation',      'corporate',
    'corporation',    'correct',        'correspondent',    'council',
    'counselor',      'counter',        'country',          'courage',
    'coverage',       'creation',       'creative',         'creature',
    'criminal',       'criteria',       'critical',         'criticism',
    'criticize',      'crucial',        'cultural',         'culture',
    'curious',        'current',        'currently',        'curriculum',
    'customer',       'dangerous',      'darkness',         'daughter',
    'decision',       'declare',        'decline',          'decrease',
    'defendant',      'defense',        'defensive',        'deficit',
    'definitely',     'definition',     'deliver',          'delivery',
    'democracy',      'Democrat',       'democratic',       'demonstrate',
    'demonstration',  'department',     'dependent',        'depending',
    'depression',     'describe',       'description',      'deserve',
    'designer',       'desperate',      'despite',          'destroy',
    'destruction',    'detailed',       'determine',        'develop',
    'developing',     'development',    'dialogue',         'difference',
    'different',      'differently',    'difficult',        'difficulty',
    'digital',        'dimension',      'direction',        'directly',
    'director',       'disability',     'disagree',         'disappear',
    'disaster',       'discipline',     'discourse',        'discover',
    'discovery',      'discrimination', 'discuss',          'discussion',
    'disease',        'dismiss',        'disorder',         'display',
    'dispute',        'distance',       'distant',          'distinct',
    'distinction',    'distinguish',    'distribute',       'distribution',
    'district',       'diverse',        'diversity',        'division',
    'divorce',        'document',       'domestic',         'dominant',
    'dominate',       'downtown',       'dramatic',         'dramatically',
    'drawing',        'earnings',       'eastern',          'economic',
    'economics',      'economist',      'economy',          'edition',
    'educate',        'education',      'educational',      'educator',
    'effective',      'effectively',    'efficiency',       'efficient',
    'elderly',        'election',       'electric',         'electricity',
    'electronic',     'element',        'elementary',       'eliminate',
    'elsewhere',      'embrace',        'emergency',        'emission',
    'emotion',        'emotional',      'emphasis',         'emphasize',
    'employee',       'employer',       'employment',       'encounter',
    'encourage',      'enforcement',    'engineer',         'engineering',
    'English',        'enhance',        'enormous',         'enterprise',
    'entertainment',  'entirely',       'entrance',         'environment',
    'environmental',  'episode',        'equally',          'equipment',
    'especially',     'essential',      'essentially',      'establish',
    'establishment',  'estimate',       'European',         'evaluate',
    'evaluation',     'evening',        'eventually',       'everybody',
    'everyday',       'everyone',       'everything',       'everywhere',
    'evidence',       'evolution',      'exactly',          'examination',
    'examine',        'example',        'excellent',        'exception',
    'exchange',       'exciting',       'executive',        'exercise',
    'exhibit',        'exhibition',     'existence',        'existing',
    'expansion',      'expectation',    'expense',          'expensive',
    'experience',     'experiment',     'explain',          'explanation',
    'explode',        'explore',        'explosion',        'exposure',
    'express',        'expression',     'extension',        'extensive',
    'external',       'extraordinary',  'extreme',          'extremely',
    'facility',       'factory',        'faculty',          'failure',
    'familiar',       'fantasy',        'fashion',          'favorite',
    'feature',        'federal',        'feeling',          'fiction',
    'fifteen',        'fighter',        'fighting',         'finally',
    'finance',        'financial',      'finding',          'fishing',
    'fitness',        'following',      'football',         'foreign',
    'forever',        'formation',      'formula',          'fortune',
    'forward',        'foundation',     'founder',          'framework',
    'freedom',        'frequency',      'frequent',         'frequently',
    'friendly',       'friendship',     'frustration',      'function',
    'fundamental',    'funding',        'funeral',          'furniture',
    'furthermore',    'gallery',        'general',          'generally',
    'generate',       'generation',     'genetic',          'gentleman',
    'gesture',        'girlfriend',     'government',       'governor',
    'gradually',      'graduate',       'grandfather',      'grandmother',
    'greatest',       'grocery',        'growing',          'guarantee',
    'guideline',      'habitat',        'handful',          'headline',
    'headquarters',   'healthy',        'hearing',          'heavily',
    'helicopter',     'helpful',        'heritage',         'herself',
    'highlight',      'highway',        'himself',          'historian',
    'historic',       'historical',     'history',          'holiday',
    'homeless',       'horizon',        'hospital',         'household',
    'housing',        'however',        'hundred',          'hunting',
    'husband',        'hypothesis',     'identification',   'identify',
    'identity',       'illegal',        'illness',          'illustrate',
    'imagination',    'imagine',        'immediate',        'immediately',
    'immigrant',      'immigration',    'implement',        'implication',
    'importance',     'important',      'impossible',       'impress',
    'impression',     'impressive',     'improve',          'improvement',
    'incentive',      'incident',       'include',          'including',
    'incorporate',    'increase',       'increased',        'increasing',
    'increasingly',   'incredible',     'independence',     'independent',
    'indicate',       'indication',     'individual',       'industrial',
    'industry',       'infection',      'inflation',        'influence',
    'information',    'ingredient',     'initial',          'initially',
    'initiative',     'innocent',       'inquiry',          'insight',
    'inspire',        'install',        'instance',         'instead',
    'institution',    'institutional',  'instruction',      'instructor',
    'instrument',     'insurance',      'intellectual',     'intelligence',
    'intense',        'intensity',      'intention',        'interaction',
    'interest',       'interested',     'interesting',      'internal',
    'international',  'Internet',       'interpret',        'interpretation',
    'intervention',   'interview',      'introduce',        'introduction',
    'invasion',       'investigate',    'investigation',    'investigator',
    'investment',     'investor',       'involve',          'involved',
    'involvement',    'Islamic',        'Israeli',          'Italian',
    'Japanese',       'journal',        'journalist',       'journey',
    'judgment',       'justice',        'justify',          'killing',
    'kitchen',        'knowledge',      'laboratory',       'landscape',
    'language',       'largely',        'lawsuit',          'leadership',
    'leading',        'learning',       'leather',          'legislation',
    'legitimate',     'liberal',        'library',          'license',
    'lifestyle',      'lifetime',       'limitation',       'limited',
    'literally',      'literary',       'literature',       'location',
    'long-term',      'machine',        'magazine',         'maintain',
    'maintenance',    'majority',       'management',       'manager',
    'manufacturer',   'manufacturing',  'marketing',        'marriage',
    'married',        'massive',        'material',         'meaning',
    'meanwhile',      'measure',        'measurement',      'mechanism',
    'medical',        'medication',     'medicine',         'meeting',
    'membership',     'mention',        'message',          'Mexican',
    'military',       'million',        'minister',         'minority',
    'miracle',        'missile',        'mission',          'mistake',
    'mixture',        'moderate',       'monitor',          'moreover',
    'morning',        'mortgage',       'motivation',       'mountain',
    'movement',       'multiple',       'musical',          'musician',
    'mystery',        'narrative',      'national',         'natural',
    'naturally',      'necessarily',    'necessary',        'negative',
    'negotiate',      'negotiation',    'neighbor',         'neighborhood',
    'neither',        'nervous',        'network',          'nevertheless',
    'newspaper',      'nomination',     'nonetheless',      'normally',
    'northern',       'nothing',        'nowhere',          'nuclear',
    'numerous',       'objective',      'obligation',       'observation',
    'observe',        'observer',       'obvious',          'obviously',
    'occasion',       'occasionally',   'occupation',       'offense',
    'offensive',      'officer',        'official',         'Olympic',
    'ongoing',        'opening',        'operate',          'operating',
    'operation',      'operator',       'opinion',          'opponent',
    'opportunity',    'opposite',       'opposition',       'ordinary',
    'organic',        'organization',   'organize',         'orientation',
    'original',       'originally',     'otherwise',        'ourselves',
    'outcome',        'outside',        'overall',          'overcome',
    'overlook',       'package',        'painful',          'painter',
    'painting',       'Palestinian',    'parking',          'participant',
    'participate',    'participation',  'particular',       'particularly',
    'partner',        'partnership',    'passage',          'passenger',
    'passion',        'patient',        'pattern',          'payment',
    'penalty',        'perceive',       'percentage',       'perception',
    'perfect',        'perfectly',      'perform',          'performance',
    'perhaps',        'permanent',      'permission',       'personal',
    'personality',    'personally',     'personnel',        'perspective',
    'persuade',       'phenomenon',     'philosophy',       'photograph',
    'photographer',   'physical',       'physically',       'physician',
    'picture',        'planning',       'plastic',          'platform',
    'pleasure',       'political',      'politically',      'politician',
    'politics',       'pollution',      'popular',          'population',
    'portion',        'portrait',       'portray',          'position',
    'positive',       'possess',        'possibility',      'possible',
    'possibly',       'potential',      'potentially',      'poverty',
    'powerful',       'practical',      'practice',         'precisely',
    'predict',        'preference',     'pregnancy',        'pregnant',
    'preparation',    'prepare',        'prescription',     'presence',
    'present',        'presentation',   'preserve',         'president',
    'presidential',   'pressure',       'pretend',          'prevent',
    'previous',       'previously',     'primarily',        'primary',
    'principal',      'principle',      'priority',         'prisoner',
    'privacy',        'private',        'probably',         'problem',
    'procedure',      'proceed',        'process',          'produce',
    'producer',       'product',        'production',       'profession',
    'professional',   'professor',      'profile',          'program',
    'progress',       'project',        'prominent',        'promise',
    'promote',        'properly',       'property',         'proportion',
    'proposal',       'propose',        'proposed',         'prosecutor',
    'prospect',       'protect',        'protection',       'protein',
    'protest',        'provide',        'provider',         'province',
    'provision',      'psychological',  'psychologist',     'psychology',
    'publication',    'publicly',       'publish',          'publisher',
    'punishment',     'purchase',       'purpose',          'qualify',
    'quality',        'quarter',        'quarterback',      'question',
    'quickly',        'quietly',        'radical',          'rapidly',
    'reaction',       'reading',        'reality',          'realize',
    'reasonable',     'receive',        'recently',         'recognition',
    'recognize',      'recommend',      'recommendation',   'recording',
    'recover',        'recovery',       'recruit',          'reduction',
    'reference',      'reflect',        'reflection',       'refugee',
    'regarding',      'regardless',     'regional',         'register',
    'regular',        'regularly',      'regulate',         'regulation',
    'reinforce',      'relation',       'relationship',     'relative',
    'relatively',     'release',        'relevant',         'religion',
    'religious',      'remaining',      'remarkable',       'remember',
    'repeatedly',     'replace',        'reporter',         'represent',
    'representation', 'representative', 'Republican',       'reputation',
    'request',        'require',        'requirement',      'research',
    'researcher',     'resemble',       'reservation',      'resident',
    'resistance',     'resolution',     'resolve',          'resource',
    'respect',        'respond',        'respondent',       'response',
    'responsibility', 'responsible',    'restaurant',       'restore',
    'restriction',    'retirement',     'revenue',          'revolution',
    'romantic',       'roughly',        'routine',          'running',
    'Russian',        'sanction',       'satellite',        'satisfaction',
    'satisfy',        'scandal',        'scenario',         'schedule',
    'scholar',        'scholarship',    'science',          'scientific',
    'scientist',      'secretary',      'section',          'security',
    'segment',        'selection',      'senator',          'sensitive',
    'sentence',       'separate',       'sequence',         'serious',
    'seriously',      'service',        'session',          'setting',
    'settlement',     'several',        'shelter',          'shooting',
    'shopping',       'shortly',        'shoulder',         'significance',
    'significant',    'significantly',  'silence',          'similar',
    'similarly',      'situation',      'slightly',         'so-called',
    'society',        'software',       'soldier',          'solution',
    'somebody',       'somehow',        'someone',          'something',
    'sometimes',      'somewhat',       'somewhere',        'sophisticated',
    'southern',       'Spanish',        'speaker',          'special',
    'specialist',     'species',        'specific',         'specifically',
    'spending',       'spiritual',      'spokesman',        'squeeze',
    'stability',      'standard',       'standing',         'statement',
    'station',        'statistics',     'stomach',          'storage',
    'straight',       'strange',        'stranger',         'strategic',
    'strategy',       'strength',       'strengthen',       'stretch',
    'strongly',       'structure',      'struggle',         'student',
    'subject',        'subsequent',     'substance',        'substantial',
    'succeed',        'success',        'successful',       'successfully',
    'suddenly',       'sufficient',     'suggest',          'suggestion',
    'suicide',        'support',        'supporter',        'suppose',
    'supposed',       'Supreme',        'surface',          'surgery',
    'surprise',       'surprised',      'surprising',       'surprisingly',
    'surround',       'survival',       'survive',          'survivor',
    'suspect',        'sustain',        'symptom',          'tablespoon',
    'taxpayer',       'teacher',        'teaching',         'teaspoon',
    'technical',      'technique',      'technology',       'teenager',
    'telephone',      'telescope',      'television',       'temperature',
    'temporary',      'tendency',       'tension',          'terrible',
    'territory',      'terrorism',      'terrorist',        'testify',
    'testimony',      'testing',        'theater',          'themselves',
    'therapy',        'therefore',      'thinking',         'thought',
    'thousand',       'threaten',       'through',          'throughout',
    'tobacco',        'together',       'tomorrow',         'tonight',
    'totally',        'tourist',        'tournament',       'towards',
    'tradition',      'traditional',    'traffic',          'tragedy',
    'training',       'transfer',       'transform',        'transformation',
    'transition',     'translate',      'transportation',   'treatment',
    'tremendous',     'trouble',        'typical',          'typically',
    'ultimate',       'ultimately',     'undergo',          'understand',
    'understanding',  'unfortunately',  'uniform',          'universal',
    'universe',       'university',     'unknown',          'unlikely',
    'unusual',        'usually',        'utility',          'vacation',
    'valuable',       'variable',       'variation',        'variety',
    'various',        'vegetable',      'vehicle',          'venture',
    'version',        'veteran',        'victory',          'village',
    'violate',        'violation',      'violence',         'violent',
    'virtually',      'visible',        'visitor',          'volunteer',
    'vulnerable',     'warning',        'wealthy',          'weather',
    'wedding',        'weekend',        'welcome',          'welfare',
    'western',        'whatever',       'whenever',         'whereas',
    'whether',        'whisper',        'widespread',       'willing',
    'withdraw',       'without',        'witness',          'wonderful',
    'working',        'workshop',       'worried',          'writing',
    'yesterday',      'yourself'
  ];

  private wordToGuess: string;
  private guessedWord: string;

  constructor(wordToGuess: string = null) {
    this.wordToGuess = wordToGuess ||
        HangmanLogic
            .words[Math.floor(Math.random() * HangmanLogic.words.length)]
            .toLowerCase();
    this.guessedWord = '.'.repeat(this.wordToGuess.length);
  }

  public guess(letter: string): number {
    if (letter.length !== 1) {
      throw new Error('A guess must consist of one letter');
    }

    if (this.guessedWord.indexOf(letter) !== -1) {
      // Already guessed this letter
      return 0;
    }

    let count = 0;
    for (let pos = 0, index = -1;
         (index = this.wordToGuess.indexOf(letter, pos)) !== -1;
         pos = index + 1) {
      this.guessedWord = this.guessedWord.substring(0, index) + letter +
          this.guessedWord.substring(index + 1, this.wordToGuess.length);
      count++;
    }

    return count;
  }

  public get word() { return this.guessedWord; };
}