# @baseUrl = http://localhost:8081/api
@baseUrl = http://training-footage.westeurope.azurecontainer.io/api

###
GET {{baseUrl}}/blobs/videos
Accept: application/json

###
GET {{baseUrl}}/blobs/images
Accept: application/json